### ISSUE TITLE
App crash on launch - iOS 13.3.1

### ISSUE THREAD

**Issue by Mattrak** [inickt/LazyMan-iOS#68] opened 2020-02-08 00:27 UTC
Tried to install with iOS App signer, AltDeploy, many times. My developper account is verified and thrust. The app crash on launch.

**Comment by JoshNotWright** [comment] 2020-02-11 00:32
Happening here too on both iOS 13.3.1 and iOS 13.4 dev b1

**Comment by inickt** [comment] 2020-02-11 05:08
I’ll see if I can reproduce this, I am keeping my devices on 13.3 for a jailbreak but I have seen some things on Twitter about it.

**Comment by JoshNotWright** [comment] 2020-02-11 05:11
I couldn’t reproduce it on Xcode for either 13.3.1 or 13.4 fyi

**Comment by inickt** [comment] 2020-02-11 05:38
@JoshNotWright So building and running the Xcode project was fine but installing the ipa wasn’t?

**Comment by JoshNotWright** [comment] 2020-02-11 05:55
Yes. It was weird. Built it multiple times and it would only crash on my iPhone.

**Comment by Mattrak** [comment] 2020-02-15 15:34
Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/FSCalendar.framework/FSCalendar | Referenced from: /private/var/containers/Bundle/Application/A047F28E-B354-4D9B-9CA8-77CBC5EE3F35/LazyMan-iOS.app/LazyMan-iOS | Reason: no suitable image found.  Did find: | /private/var/containers/Bundle/Application/A047F28E-B354-4D9B-9CA8-77CBC5EE3F35/LazyMan-iOS.app/Frameworks/FSCalendar.framework/FSCalendar: code signature invalid for '/private/var/containers/Bundle/Application/A047F28E-B354-4D9B-9CA8-77CBC5EE3F35/LazyMan-iOS.app/Frameworks/FSCalendar.framework/FSCalendar' | /private/var/containers/Bundle/Application/A047F28E-B354-4D9B-9CA8-77CBC5EE3F35/LazyMan-iOS.app/Frameworks/FSCalendar.framework/FSCalendar: code signature invalid for '/private/var/containers/Bundle/Application/A047F28E-B354-4D9B-9CA8-77CBC5EE3F35/LazyMan-iOS.app/Frameworks/FSCalendar.framework/FSCalendar' | /private/var/containers/Bundle/Application/A047F28E-B354-4D9B-9CA8-77CBC5EE3F35/LazyMan-iOS.app/Frameworks/FSCalendar.framework/FSCalendar: stat() failed with errno=1 | /p
Triggered by Thread:  0

**Comment by Mattrak** [comment] 2020-02-15 16:22
[It looks very much like this :(](https://github.com/Alamofire/Alamofire/issues/3051#issuecomment-580139830)

> Are you using a non-developer Apple ID to install the app to your phone? It looks like iOS 13.3.1 has broken apps installed with free Apple IDs, but only if they contain embedded frameworks. If it's possible to link all your dependencies as static libraries rather than frameworks (for example, if you're using Cocoapods you can remove use_frameworks! from your Podfile), that should fix the issue for now.

**Comment by inickt** [comment] 2020-03-11 02:05
Looks like this should be fixed in 13.4. (https://github.com/Alamofire/Alamofire/issues/3051). I looked at switching the Pods to `use_modular_headers!` but the app was still crashing and I don't think its going to be worth fixing if its just a bug on this version. If this is still an issue for 13.4 I can revisit.

**Closed by inickt** 2020-03-11 02:05 UTC
